apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wazuh.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "wazuh.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "wazuh.name" . }}
    spec:
      tolerations:
        - operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: wazuh
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi
          ports:
            - containerPort: {{ .Values.service.port }}
